name: Triage Board Management

on:
  issues:
    types:
      - opened
      - reopened
      - transferred

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/add-to-project@2e5cc851ca7162e9eb510e6da6a5c64022e606a7
        with:
          project-url: https://github.com/orgs/usnistgov/projects/25
          github-token: ${{ secrets.COMMIT_TOKEN }}
