name: Triage Board Management

on:
  issues:
    types:
      - opened
      - reopened
      - transferred

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/add-to-project@0609a2702eefb44781da00f8e04901d6e5cd2b92
        with:
          project-url: https://github.com/orgs/usnistgov/projects/25
          github-token: ${{ secrets.COMMIT_TOKEN }}
