on:
  label:
    types: [created,deleted,edited]
  push:
    branches:
      - main
    paths:
      - '.github/labels.json'
name: Create Default Labels
jobs:
  labels:
    name: DefaultLabelsActions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247
      - uses: lannonbr/issue-label-manager-action@e8dbcd8198e86a1e98d5372e55db976fed9ba6f7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
